// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIV0mxlAWHE-LSnScmr1k457bZLpCqSMY',
    appId: '1:545387627332:web:a8344dd0306bdc191f4d11',
    messagingSenderId: '545387627332',
    projectId: 'volters-app',
    authDomain: 'volters-app.firebaseapp.com',
    storageBucket: 'volters-app.appspot.com',
    measurementId: 'G-6KNC7PFW1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9w_8v8t2J5fiJobA_r4flAq7zNoCM9iM',
    appId: '1:545387627332:android:b19d5af2c46ae0f11f4d11',
    messagingSenderId: '545387627332',
    projectId: 'volters-app',
    storageBucket: 'volters-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC92G2rRXFy7NTbFC2gYa4pgLpFPGBJve0',
    appId: '1:545387627332:ios:a1147a45df2654c71f4d11',
    messagingSenderId: '545387627332',
    projectId: 'volters-app',
    storageBucket: 'volters-app.appspot.com',
    androidClientId: '545387627332-t3u7l32jfbd6vjsmjpn4c7rjeoc8u4d1.apps.googleusercontent.com',
    iosClientId: '545387627332-te17n8gm63cofimmuadba54c7dna5i0j.apps.googleusercontent.com',
    iosBundleId: 'br.com.volters.volters',
  );
}
